cotemote/cote

- jiho/셔틀버스.cpp
- 가장 먼저로 했던 것은, 문자열로 입력된 시간들을 모두 '순수 분'으로 바꿔주는 함수를 만드는 것이었습니다. (makeMinute)
- 그리고 이 '순수 분'을 다시 문자열로 바꾸어주는 함수(makeTime)를 만들었습니다.
- 본격적으로 문제를 풀면서 간과했던 지점은, '콘이 탈 수 있는 곳을 찾기'가 아니라, '어떻게든 비집고 콘을 태우기'라는 점이었습니다. 그냥 빈 자리에 넣으니까 테케 실패했습니다.
- 콘을 어떻게 비집고 태울 수 있을까를 고민하다가, 다음과 같은 로직으로 작성했습니다.
- 최대한 버팅기다가 차가 오는 타이밍에 맞춰서 나가기
- 버스 타이밍에 맞춰 나갔을 때 대기자로 인해 못 타는 경우라면, 꼴찌 대기자보다 1분 일찍 오기
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17678)
> [17678] 셔틀버스 (wlgh1553)

- jiho/캐시.cpp
- 문제에서는 LRU 알고리즘에 대해 따로 자세히 설명하고 있지 않습니다.
- LRU 알고리즘을 잘 기억하고 있으시다면 저처럼 헤매지 않으실 것 같습니다.
- 저는 캐시 리스트에서, 가장 최신에 사용한 도시 이름의 우선순위를 높이는 것을 깜빡하여 오답 코드를 제출했었습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17680)
> [17680] 캐시 (wlgh1553)

- jiho/다트게임.cpp
- 입력값을 파싱하기 위해 `parse`함수를 만들어 사용했습니다.
- 그리고 이 함수의 return을 위해 Dart 구조체를 만들어 사용했습니다.
- C++로 문자열 파싱할 때마다 힘들어 죽겠습니다. 얼른 익숙해져야겠어요.
- 실제 점수 계산하는 부분은 그래도 파싱에 비해 금세 풀어낼 수 있었던 것 같습니다. (물론 문제가 잘 안 읽히긴 해요..)
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17682)
> [17682] 다트 게임 (wlgh1553)

- cjeongmin/다트게임.js
- 요구사항에 맞게 단순 구현하는 문제입니다.
- 정규표현식 이용해서 문자열 파싱을 진행하고 결과를 이용해서 요구사항에 맞게 구현했습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17682)
> [17682] 다트 게임 (cjeongmin)

- cjeongmin/캐시.js
- LRU 캐시를 구현하는 문제였습니다.
- JS 에서 Map 은 삽입한 순서대로 순회가 되는 특성을 이용했습니다.
- 문제 조건으로 캐시 사이즈가 0인 경우가 있어 그 부분만 특별히 예외처리 했습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17680)
> [17680] 캐시 (cjeongmin)

- sanghyeon/Programmers17682.py
- 현재 문자가 '*'일 경우 이전 숫자에 영향을 주므로 list에 계산된 현재 값들을 저장해줬습니다
- 숫자가 10일 경우에 대해서 예외 처리를 해주었습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17682?language=python3)
> [17682] 다트 게임(shl0501)

- sanghyeon/Programmers17678.py
- sanghyeon/Programmers17682.py
- 셔틀 버스 시간대마다 탈 수 있는 인원의 정보를 저장했지만 알고보면 전체 승객 중 가장 마지막에만 탄 승객의 정보만 알면되는 문제
- 문제를 더 단순화해서 푸는 연습이 필요하다고 느껴짐
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17678?language=python3)
> [17678] 셔틀 버스 (shl0501)

- cjeongmin/비밀지도.js
- OR 연산 이후에, 해당하는 문자로 변경했습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17681?language=javascript)
> [17681] 비밀지도 (cjeongmin)

- jiho/비밀지도.cpp
- 비트로 or 연산을 하는 문제
- 10진수를 2진수로 바꿔주는 C++ 내장 함수 없나 찾아봤으나, 없었음. 결국 직접 2로 나눠가며 구현
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17681)
> [17681] 비밀지도 (wlgh1553)

- jiho/수식_복원하기.cpp
- 10진법 <-> n진법 <-> 문자열 이 것들의 변환을 조금 비효율적으로 구현한 것 같습니다.
- C++의 stoi 함수는 n진법으로 변환 불가한 경우(예를 들어 3이 포함된 문자열을 2진수로 변환하는 경우) 자꾸 죽었습니다. 이것 예외 처리 안 해줘서 한참을 헤맸습니다.
- 또 약간 중첩 반복문을 돌아야할 일이 많아 헷갈렸던 것 같습니다. 깔금하게 하려고 최대한 함수를 만들고자 했는데, 이로 인해 오히려 불필요한 반복을 많이 하게 된 것 같아 아쉬움이 남습니다.
- 반성할 점: 조금 더 생각해서 코드 큰 그림을 그리고 시작하자.. (문제 전체를 이해하기도 전에 작은 함수부터 만들었더니 나중 가서 우왕좌왕 했음.) 
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/340210?language=cpp)
> [340210] [PCCP 기출문제] 4번 / 수식 복원하기 (wlgh1553)

- cjeongmin/뉴스클러스터링.js
- 문제 요구사항에 맞게 구현하는 문제였습니다.
- 중복 집합 연산이 가능하게끔 합집합, 교집합 연산을 구현 했습니다.
- 그리고 자카드 유사도 계산시 분모가 0이 되는 경우만 따로 예외 처리를 추가했습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17677?language=javascript)
> [17677] 뉴스 클러스터링 (cjeongmin)

- jiho/프렌즈4블록.cpp
- 하나씩 차근차근 구현했습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17679)
> [17679] 프렌즈4블록 (wlgh1553)

- jiho/뉴스_클러스터링.cpp
- 교집합 합집합이 공집합인 경우에 대한 예외처리를 안 해줘서 한 번 틀렸습니다.
- 교훈은 문제를 잘 읽자
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17677)
> [17677] 뉴스 클러스터링 (wlgh1553)

- jiho/추석트래픽.cpp
- 시작 시간이 아닌 끝 시간을 기준으로 탐색했어야 했는데, 시작 시간을 기준으로 탐색하여 헤맸습니다.
- 문제에서 정렬하여 제공한 것에는 이유가 있다는 것을 깨달았습니다.
- 이상입니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17676)
> [17676] 추석트래픽 (wlgh1553)

- cjeongmin/수식-복원하기.js
- 각 수식에 사용된 숫자 중 가장 큰 숫자를 찾습니다. 가장 큰 숫자 `n` 이라면, 최소 진법은 `n + 1` 입니다.
- 최소 진법부터, 해당 진법이 모든 수식에서 유효한지 확인합니다.
- 이후, 가능한 진법이 하나인 경우, 해당 진법을 사용해 지워진 결괏값을 계산하고, 여러 개인 경우, 모든 진법에서 동일한 결괏값이 도출되면 그 값을 사용하고 그렇지 않으면 ?로 표시합니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/340210)
> [340210] [PCCP 기출문제] 4번 / 수식 복원하기 (cjeongmin)

- youngjun/week2/뉴스_클러스터링.py
- 두 글자씩 자르고, 각 두 글자 콤비에 대해 isalpha로 알파벳 여부를 필터링했습니다.
- collections의 Counter를 사용하여 다중교집합, 다중합집합 생성 함수를 만들고, 이를 사용하여 자카드 유사도를 계산하도록 했습니다.
- 교집합과 합집합 변수명을 고민 끝에 kyo, hap 으로 명명한 것이 이 문제의 킥이었습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17677)
> [17677] 뉴스 클러스터링 (zizonyoungjun)

- youngjun/week2/추석_트래픽.py
- answer의 max 값은 len(lines)
-  answer는 무조건 특정 로그의 시작 혹은 끝 시점
- 답이 될 수 있는 구간을 intervals 딕셔너리로 만들고, 각 로그에 대해 범위가 겹치는 구간의 카운트를 1씩 올리면 구할 수 있음
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17676)
> [17676] 추석 트래픽 (zizonyoungjun)

- jiho/n진수_게임.cpp
- 라이브 코딩테스트 연습 겸 중얼 거리면서 풀어봤습니다.
- 접근 방법이 떠오르지 않을 땐 질문을 할 수 있어야하는데, 혼자 더 고민하게 되는 것 같습니다. 연습이 필요해보입니다.
- reverse함수는 algorithm 헤더에 있음을 다시 배웠습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17687)
> [17687] n진수 게임 (wlgh1553)

- cjeongmin/n진수_게임.js
- 문제에서 요구하는 대로 단순 구현했습니다. 자바스크립트에서 진수 변환 내장 함수가 있어서 해당 함수를 이용했습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17687)
> [17687] n진수 게임 (cjeongmin)

- jiho/파일명_정렬.cpp
- 파싱조차 내장함수 없이 일일이 구현해봤습니다.
- 그러다보니 함수가 많이 길어졌네요..
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17686)
> [17686] 파일명 정렬 (wlgh1553)

- jiho/압축.cpp
- 문제를 꼼꼼히 이해했어야했는데, 그러지 않고 바로 풀이부터 시작하여 좀 헤맸습니다.
- 문제만 이해하면 차근차근 풀어낼 수 있습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17684)
> [17684] 압축 (wlgh1553)

- cjeongmin/파일명_정렬.js
- 파일 이름은 HEAD, NUMBER, TAIL 3가지로 나누고, 요구사항대로 정렬했습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17686?language=javascript)
> [17686] 파일명 정렬 (cjeongmin)

- cjeongmin/압축.js
- 알파벳 A부터 Z까지를 초기 사전에 추가합니다.
- msg를 처음부터 끝까지 순회하면서, 현재 인덱스부터 시작하여 사전에 존재하는 가장 긴 문자열을 찾습니다.
- 찾은 문자열의 사전 번호를 결과 배열에 추가합니다.
- 그 다음, 찾은 문자열 뒤에 이어지는 문자와 함께 새 문자열을 만들어 사전에 추가합니다.
- 이를 반복하고 최종적으로 압축된 결과인 번호들의 배열을 반환합니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17684?language=javascript)
> [17684] 압축 (cjeongmin)

- youngjun/week3/압축.py
- 아스키코드를 활용해서 A-Z까지의 초기 사전을 만듭니다
- 문자열을 순회하면서 현재 위치에서 시작하는 가능한 가장 긴 문자열을 찾습니다
- 찾은 문자열의 색인 번호를 answer 배열에 추가하고, 그 다음 문자를 포함한 새로운 문자열을 사전에 추가합니다
- 처리된 문자열 길이만큼 인덱스를 이동합니다
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17684)
> [17684] 압축 (zizonyoungjun)

- cjeongmin/방금그곡.js
- 제공되는 음악 정보를 이용해서 음표 단위로 배열을 생성하는 함수를 이용해서, 음표 단위로 매칭을 합니다.
- 곡 재생 시간만큼 음표 배열을 다시 만듭니다.
- 이후, 매칭에서 편의를 위해서 `join`함수를 이용해서 문자열로 만들어서 찾았으며, `#`이 붙는 경우로 인해 문제 생기는 경우를 처리하기 위해 패턴 문자열 앞뒤에 ','를 추가하였습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17683?language=javascript)
> [17683] 방금그곡 (cjeongmin)

- cjeongmin/자동완성.js
- 각 단어를 Trie 자료구조에 삽입할 때, 접두사별 등장 횟수를 기록합니다.
- 단어를 검색할 때, Trie를 순회하면서 접두사의 등장 횟수가 1인 지점에 도달하면 해당 위치까지의 길이가 그 단어의 유일성을 결정하는 최소 타자 수가 됩니다.
- 모든 단어에 대해 유일성을 보장하는 최소 타자 수를 합산하여 최종 답을 구합니다.
- 즉, Trie를 이용해 각 접두사의 빈도를 관리하고, 각 단어별로 충분히 구별 가능한 접두사의 길이를 계산하는 방식입니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17685?language=javascript)
> [17685] 자동완성 (cjeongmin)

- youngjun/week4/실패율.py
- for 문으로 1~N 스테이지에 대해 도달한 사람 수를 나타내는 딕셔너리 생성
- stages의 각 수에 대해 for문으로 딕셔너리 value 값 +1 
- 실패율 : 해당 스테이지 value - 다음 스테이지 value / 해당 스테이지 value
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/42889)
> [42889] 실패율 (zizonyoungjun)

- youngjun/week4/후보키.py
- combinations로 가능한 모든 컬럼 조합을 만들고,
- 모든 조합에 대해 유일성 검사를 하고, 이를 통과한 조합에 대해 최소성 검사 진행
- 유일성 검사는 새로운 튜플을 생성하고, 기존 행 수와 비교하여 중복 제거된 것이 없는지 확인하는 방식으로 구현
- 최소성 검사는 유일성을 통과한 조합들끼리 부분집합 관계를 확인해서, 더 작은 조합이 이미 후보키라면, 그것을 포함하는 큰 조합은 제외
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/42890)
> [42890] 실패율 (zizonyoungjun)

- cjeongmin/길_찾기_게임.js
- 트리를 만들기 전에, 좌표 순으로 정렬했습니다.
- 이후에 좌표에 따라 트리를 만들고, 전위 순회, 후위 순회하는 함수를 구현했습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/42892?language=javascript)
> [42892] 길 찾기 게임 (cjeongmin)

- cjeongmin/실패율.js
- 플레이어의 스테이지 정보를 정렬한 후, 이진 탐색을 통해 특정 스테이지를 넘은 플레이어 수를 찾습니다.
- 각 스테이지별로 (해당 스테이지에 머문 플레이어 수) / (해당 스테이지에 도달한 플레이어 수)를 계산합니다.
- 계산된 실패율을 기준으로 스테이지 번호를 내림차순 정렬합니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/42889?language=javascript)
> [42889] 실패율 (cjeongmin)

- jiho/길찾기게임.py
- 파이썬 배운 점
1. n번째부터 순회하고 싶은 경우
2. enumerate()
3. 정렬방법
4. 재귀 깊이 설정 방법
- 재귀로 함수 짜는 게 되게 어려워서 c정민님 코드를 참조했습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/42892)
> [42892] 길 찾기 게임 (wlgh1553)

- jiho/길찾기게임.py
- jiho/실패율.py
- 파이썬 새로 배운 점
1. 파이썬은 `cnt++`이 없다. `cnt+=1`해야함.
2. 리스트 길이는 len()함수를 써야함
3. 리스트 요소 추가는 append를 써야함
4. 삼항 연산자 `"양수" if a > 0 else "음수"`
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/42889)
> [42889] 실패율 (wlgh1553)

- jiho/후보키.py
1. 집합 자료구조 초기화는 `a = set()`처럼 해줘야 한다. (`a = ()`는 빈 튜플)
2. 집합 자료구조 초기화 시 값을 넣고 싶으면 `a={1,2,3}`을 해줘야 한다. (`a={}`는 빈 딕셔너리)
3. itertools의 combinations에서 조합을 구해올 수 있다.
4. `any` 함수가 있다. 마치 JS의 `some` 같은 친구. `any` 내부에 for문으로 배열을 만들어 바로 넣을 수도 있다. `any(3 < num for num in arr)`
5. 부분집합 판별은 issubset함수를 사용한다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/42890)
> [42890] 후보키 (wlgh1553)

- jiho/방금그곡.py
- not연산자를 써야한다. !가 아니고.
- `#` 을 생각 안 하고 그냥 부분문자열 판단을 해버렸다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/17683)
> [17683] 방금그곡 (wlgh1553)

- cjeongmin/후보키.js
- 가능한 조합을 비트로 표현해서, 가능한 조합을 만들고 조합의 수가 유일성이 보장이 되면 아래 내용에 따라 추가합니다.
- 추가할 때, 부분 집합 여부를 판별해서 최소성이 보장되면 추가합니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/42890?language=javascript)
> [42890] 후보키 (cjeongmin)

- yujin/실패율.js
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/42892)
> [42889] 실패율 (Ujaa)

- yujin/길 찾기 게임.js
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/42892)
> [42892] 길 찾기 게임 (Ujaa)

- cjeongmin/오픈채팅방.js
- uid별 닉네임을 기억하고 해당 닉네임으로 결과를 만들었습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/42888?language=javascript)
> [42888] 오픈채팅방 (cjeongmin)

- cjeongmin/미로 탈출 명령어.js
- 문제에서 주어진 우선순위에 따라서 탐색했습니다.
- 현재 주어진 상태에서 도착지까지 N회안에 도착이 가능한지 추가적으로 판별합니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/150365)
> [150365] 미로 탈출 명령어 (cjeongmin)

- cjeongmin/표 병합.js
- 유니온 파인드를 이용해서 셀의 상태를 관리했습니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/150366)
> [150366] 표 병합 (cjeongmin)

- cjeongmin/표현 가능한 이진트리.js
- 숫자를 이진수로 변환한 후에 포화 이진 트리의 특성을 이용해서 높이를 알아내고, 해당 높이만큼 더미 노드로 채웁니다.
- 포화 이진 트리의 노드 개수 특성상 중앙은 루트 노드이므로 해당 루트 노드에서부터 탐색을 시작해서 트리가 구성이 가능한지 판별합니다.
- [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/150367)
> [150367] 표현 가능한 이진트리 (cjeongmin)

- sanghyeon/bj17352.py
- union find 알고리즘을 사용하여 문제를 해결하였습니다.
- [문제 링크](https://www.acmicpc.net/problem/17352)
> [17352] 여러분의 다리가 되어 드리겠습니다! (shl0501)

- cjeongmin/여러분의 다리가 되어 드리겠습니다.js
- 그래프에서 주어진 간선을 통해서 두 컴포넌트로 만들고, 두 컴포넌트의 아무 정점을 출력하면 되는 문제로 유니온 파인드 이용해서 각 노드들을 연결
- 이후에 경로 압축을 통해서 두 컴포넌트로만 데이터가 남도록 하고, 그 두 컴포넌트에 해당하는 아무 노드 출력
- [문제 링크](https://www.acmicpc.net/problem/17352)
> [17352] 여러분의 다리가 되어 드리겠습니다 (cjeongmin)

- jiho/여러분의 다리가 되어 드리겠습니다!.py
- 까먹은 유니온 파인드 다시 학습 ([요 블로그](https://yoongrammer.tistory.com/102) 굉장히 좋았음)
- 자꾸 시간초과 떠서 엥 했는데, 알고보니 파이썬은 `input()`말고 `sys.stdin.readline()`해줘야 빨리 입력받을 수 있었음
- [문제 링크](https://www.acmicpc.net/problem/17352)
> [17352] 여러분의 다리가 되어 드리겠습니다 (wlgh1553)

- chichoc/15665_N과M(11).js
- chichoc/17352_여러분의 다리가 되어 드리겠습니다!.js
- 매번 주어진 숫자 중에서 하나씩 선택해 누적하는 방식으로 구현하였습니다.
- 오름차순이 아닌 사전순이라 언급되어 sort()만 사용했는데 틀려서 의문입니다.
- [문제 링크](https://www.acmicpc.net/problem/15665)
> [15665] N과 M (11) (chichoc)

- chichoc/1563_개근상.js
- 처음에는 모든 경우의 수 (3^N) - 개근상이 아닌 경우를 빼서 구해볼까 싶었지만, 개근상이 아닌 경우가 너무 많았습니다.
- 어떠한 값으로 나눈 나머지를 출력하는 경우 대다수 dp지만 점화식을 어떻게 짜야할지 감이 안 와 풀이를 참고했습니다...
- [문제 링크](https://www.acmicpc.net/problem/1563)
> create [1563] 개근상 (chichoc)

- yujin/N과 M.py
> Create N과 M.py

- sanghyeon/문자열 폭발.py
1번 예시를 보고 문제를 잘못 이해해서 문자를 하나씩 없애는줄 알았지만 실제는 두번째 문자열 그대로 존재할 때만 없는 것
잘못 풀다가 안 사실은 파이썬에서 문자열을 붙이는 동작은 기존 문자열을 복사하는 과정이 필요하므로 문자열의 길이에 해당하는 O(K)가 소요된다.
- [문제 링크](https://www.acmicpc.net/problem/9935)
> [9935] 문자열 폭발(shl0501)

- sanghyeon/숨박꼭질2.py
visited여부를 체크만 하면 되는 줄 알았지만 모든 경우의 수를 카운팅 해야하므로, 같은 시간에 다른 루트로 방문한 경우도 카운팅해줘야 한다는 것이 포인트인듯 하다
- [문제 링크](https://www.acmicpc.net/submit/12851)
> [12851] 숨박꼭질2(shl0501)

- sanghyeon/bj13172.py
- sanghyeon/bj30805.py
처음에는 최장 공통 수열 알고리즘을 사용해서 푸는 것이라 생각했지만 시간초과가 남.
따라서 답지를 참고한 결과, 두 배열에서 겹치는 숫자를 찾아가며 재귀로 푸는 것이었음.
가장 긴 것을 찾는 것이 아니라 사전순으로 가장 뒤에 있는 공통 수열을 찾는 문제라서 이렇게 풀 수 있는듯함.
- [문제 링크](https://www.acmicpc.net/problem/30805)
> [30805] 사전 순 최대 공통 부분 수열 (shl0501)

- jiho/문자열 폭발.py
- 처음에는 시간 생각 안 하고 이렇게 구현했습니다.
```py
inputStr = input()
boom = input()
while boom in inputStr:
inputStr = inputStr.replace(boom, "")
if len(inputStr) == 0:
print("FRULA")
else:
print(inputStr)
```
- 그러나 시간 초과가 발생하고,, 
- stack을 사용해 맨 뒤만 검사해주기로 했습니다.
- 하지만 스택에서 pop할 때 이렇게 부분 리스트 저장을 하니 또한번 시간 초과가 났습니다. `stack = stack[:-len(boom)]`
- 직접 하나씩 pop해줘야 했습니다.         
```py
for _ in range(len(boom)):
stack.pop()
```
- [문제 링크](https://www.acmicpc.net/problem/9935)
1년 전의 한을 해결했습니다.
> [9935] 문자열 폭발(wlgh1553)

- jiho/사전 순 최대 공통 부분 수열.py
- 고민해보다가,, 도저히 안 떠올라서 답지 힌트를 얻었습니다.
- 처음에는 재귀를 아래처럼 돌렸습니다. 최댓값이 안 나오면 그 다음 인덱스부터 찾아보려고 했습니다.
```py
def solution(A, B):
if len(A) == 0 or len(B) == 0:
return []
Amax, Bmax = max(A), max(B)
Aidx, Bidx = A.index(Amax)+1, B.index(Bmax)+1
if Amax == Bmax:
return [Amax] + solution(A[Aidx:], B[Bidx:])
elif Amax < Bmax:
return solution(A, B[Bidx:])
else:
return solution(A[Aidx:], B)
```
- 그러나 틀렸습니다를 받았고, 다시 보니 굳이 그 다음 인덱스부터 찾을 필요가 없겠더라구요. 그래서 최종적으로 답안이 나왔습니다.
- 죄송합니다.
- [문제 링크](https://www.acmicpc.net/problem/30805)
> [30805] 사전 순 최대 공통 부분 수열 (wlgh1553)

- jiho/숨바꼭질2.py
- 밥 먹었습니다. (bfs)
- 근데 이제 방문 확인을 true/false로 해주지 않고, 가능한 경우의수를 넣어주었습니다.
- [문제 링크](https://www.acmicpc.net/problem/12851)
> [12851] 숨박꼭질2(wlgh1553)

- chichoc/9935_문자열 폭발.js
처음에 골드치고 간단하다 싶더니 역시나 메모리 초과했습니다.
DP 밖에 생각이 안나 힌트 보고 스택으로 풀고자 했지만,,스택 두 개를 가지고 풀다가 꼬여 AI의 힘을 빌려 풀었습니다,,
- [문제 링크](https://www.acmicpc.net/problem/9935)
> [9935] 문자열 폭발 (chichoc)

- chichoc/12851_숨바꼭질 2.js
- 테케1 예시 하나 밖에 안 떠올라 AI의 힘을 빌려 이해했습니다..
- 처음에 간단하게 BFS로 구현했다가 시간초과가 발생go visited 추가했습니다.
- 하지만 여전히 시간초과가 발생하였고 shift 문제라 판단되지만 해결책을 찾지 못해 ㅁㅑ의 힘을 빌렸습니다..
- [문제 링크](https://www.acmicpc.net/problem/12851)
> [12851] 숨바꼭질 2 (chichoc)

- chichoc/30805_사전 순 최대 공통 부분 수열.js
매번 슬라이싱해서 저장하는 로직이 메모리초가 날까봐 걱정됐지만 잘 통과했습니다,,
추후 더 효율적인 풀이 찾아보겠습니당
- [문제 링크](https://www.acmicpc.net/problem/30805)
> [30805] 사전 순 최대 공통 부분 수열 (chichioc)

- yujin/숨바꼭질 2.py
> Create 숨바꼭질 2.py

- yujin/사전 순 최대 공통 부분 수열.py
백트래킹 문제인줄 알았는데 너무 안 풀려서 gpt한테 물어보니 dp로 풀라고 했는데 어떻게 풀어도 계속 틀렸습니다. 다른 사람들 풀이 찾아보니 그냥 최대값 찾는 과정을 array 잘라서 반복하면 된다는 사실을 알게 되었습니다.
- [문제 링크](https://www.acmicpc.net/problem/30805)
> Create 사전 순 최대 공통 부분 수열.py

- sanghyeon/bj14284.py
dijkstra 문제
heapq와 for문을 사용해 구현할 수 있으며, heapq를 사용해 구현하였습니다.
- [문제 링크](https://www.acmicpc.net/problem/14284)
> [bj14284] 간선 이어가기 2 (shl0501)

- jiho/게리맨더링2.py
- 5번 바깥의 점인지 판별할 때에는 외적 사용해서 판단해줬습니다.
- 87퍼에서 틀렸는데, 도저히 이유를 모르겠어서 찾아보니 이런 반례가 있었습니다. https://www.acmicpc.net/board/view/152220
- 단순히 문제에 나온 조건대로 if문 분기 아래처럼 해주면 예외가 발생하는 것이었습니다.
```py
def counter(x, y, d1, d2):
global arr, n
cnt = [0] * 5
for r in range(1, n + 1):
for c in range(1, n + 1):
area = 5
if checkInRect([x, y], [x + d1, y - d1], [x + d1 + d2, y - d1 + d2], [x + d2, y + d2], [r, c]):
area = 5
elif r < x + d1 and c <= y:
area = 1
elif r <= x + d2 and c > y:
area = 2
elif r >= x + d1 and c < y - d1 + d2:
area = 3
elif r > x + d2 and c >= y - d1 + d2:
area = 4
cnt[area - 1] += arr[r-1][c-1]
return cnt
```
- 이를 해결하기 위해 5를 만나면 break되는 반복문을 돌려주었습니다.
- [문제 링크](https://www.acmicpc.net/problem/17779)
> [17779] 게리맨더링 2 (wlgh1553)

- cjeongmin/게리멘더링.js
- 문제 요구사항대로 단순히 구현하고 제출했었다가 오답이 되었습니다.
- 어떤 부분이 문제인가 여러 반례들 찾아보다가 기존 방식에서는 영역이 겹치는 문제가 있었고 해당 문제를 해결하니 통과했습니다.
- 위 사항을 제외하고는 요구사항대로 구현하고 모든 경우를 확인하는 방식으로 해결되었습니다.
- [문제 링크](https://www.acmicpc.net/problem/17779)
> [17779] 게리멘더링 (cjeongmin)

- 간선-이어가기.js
- 다익스트라로 해결했습니다.
- [문제 링크](https://www.acmicpc.net/problem/14284)
> [14284] 간선 이어가기 (cjeongmin)

- sanghyeon/bj20056.py
board의 경계를 넘어갔을 때 한바퀴 돌아서 돌아온다는 것을 알지 못해서 헤맸다
그 부분만 잘 처리하면 규칙에 맞춰서 구현하는 것은 어렵지 않음
따로 board를 생성하고, 복사하고 하는 반복적인 작업이 있음에도 시간복잡도를 고려하지 않아도 됨
- [문제 링크](https://www.acmicpc.net/problem/20056)
> [bj20056] 마법사 상어와 파이어볼 (shl0501)

- jiho/간선_이어가기2.py
- `이때, 특정 정점 s와 t가 연결이 되는 시점에서 간선 추가를 멈출 것이다.`라는 조건 때문에 약간의 혼란을 겪었습니다. 처음엔 간선을 입력 순서대로 추가해나가다가, s-t가 연결되는 순간의 최솟값을 찾으라는줄 알았습니다.
- 하지만 다시 읽어보니 `간선의 순서를 조정`해도 된다는 조건이 있었습니다. 문제를 잘 읽어야겠습니다.
- 다익스트라를 1년 전에 공부했었는데, 다 까먹어서 새로 공부했습니다. 여기에 올리는 풀이처럼 get_smallest_node 함수에서 for문 순회를 해주는 방법으로 처음에 구현해봤으며, 이후 상현님의 코드를 보고 heapq를 사용해보았습니다. 
- 처음 제출한 것이 for방식, 두번째 제출한것이 heapq사용방식입니다. 메모리를 더 쓰고 시간이 줄어듭니다.
- [문제 링크](https://www.acmicpc.net/problem/14284)
> [14284] 간선 이어가기 (wlgh1553)

- chichoc/14284_간선 이어가기 2.js
- 대표적인 다익스트라 유형
- 인데 너무 오랜만에 접해 정리한 자료 참고 후 풀었습니다
- 매번 큐를 정렬하지 않고 직접 구현한 우선순위큐를 활용하면 시간복잡도가 더 나아질 것 같아 추후 도전해보겠습니당
- [문제 링크](https://www.acmicpc.net/problem/14284)
> [14284] 간선 이어가기 2 (chichoc)

- yujin/간선 이어가기 2.py
> Create 간선 이어가기 2.py
